config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { :registrations => "users/registrations" }

  resources :discussions do
    resources :opinions do
      get :participation
    end
  end





  devise_scope :user do
    authenticated :user do
      root 'discussions#index', as: :authenticated_root
    end
    unauthenticated do
      root 'users/registrations#new', as: :unauthenticated_root
    end
  end
end

app/models/discussion.rb
class Discussion
	include Mongoid::Document
	include Mongoid::Timestamps
	include Mongoid::Slug



	field :title
	field :shown, type: Boolean, default: true
	field :proposal_enabled, type: Boolean, default: false
	slug  :title, :history => true
	has_many :opinions
	index({ starred: 1 })
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_discussion, only: [:show, :create, :layout]



  def index

    hash = {}
    Opinion.all.not.where(:body => nil).each do |opinion|
      hash[opinion] = opinion.absolute_relevancy()
    end

    @opinions = hash.sort_by {|_key, value| value}.reverse.to_h

  end
  # GET /discussions/1
  def show
  end

  def new
  @discussion = Discussion.new
  end

  def create
   @discussion = Discussion.create(discussion_params)
  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find  params[:id]
      @order_by = params[:order_by]
      @root = @discussion.opinions.where(:parent_opinion_id == nil).first
    end

    # Only allow a trusted parameter "white list" through.
    def discussion_params
      params.require(:discussion).permit(:title, :proposal_enabled)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/index.html.erb
<div id="div-title" class="container center">
  <h2 id="title-text", class="blue-text text-ligthen-2">Opiniões sobre as Discussões</h2>
</div>


<div class="row">
  <% @opinions.take(12).each do |opinion, value|%>
      <div class="col s12 m6 l4">
        <div class="card white">
          <div class="card-content black-text flow-text">
            <span class="card-title"><p><%= link_to "#{opinion.discussion.title}",   discussion_path(opinion.discussion, :order_by => 'relevance') %>
            </p></span>
            <div class="divider"></div>
            <span class="card-body"><p><%= link_to "#{opinion.body}",   discussion_opinion_path(opinion.discussion, opinion) %>
            </p></span>
            </div>

          <div class="card-action">
            <p><span class="date"><%= opinion.user.name %> em <%=
              distance_of_time_in_words(Time.now, opinion.updated_at) %></span></p>
             <p><span class="relevancy">Relevância: <%= opinion.absolute_relevancy.round(8) %></span></p>
          </div>
      </div>
      </div>
   <% end %>
</div>
          

app/views/discussions/show.html.erb
<%= javascript_tag do %>
  createHeader();




  if ("<%= @order_by %>" == "history")
  {
    orderHistory();
  }

  if ("<%= @order_by %>" == "relevance")
  {
    orderRelevance();
  }






 function createHeader(){

  // Creating Div of Title
  div_title = $("<div>", {id: "div-title", class:"container center"});


  // Creating Text of title
  tex_title = $("<h2>", {id: "title-text", class:"blue-text text-lighten-2"});

  //Adding Text of Discussion
  tex_title.text("<%=@discussion.title%>")


  //Append Div of Title on Discussion Div
  div_title.append(tex_title)


  //Append Div of Title on Body
  $("body").append(div_title)


  // Create a Container
  container = $("<div>", {class: "container"});

  // Append Container to Body
  $("body").append(container)


  // Create a Box Container
  box = $("<div>", {class: "box"});

  container.append(box);

  // Create a Main
  main = $("<div>", {class: "main"});

  box.append(main);

  }



  function orderHistory() {

  <% stack = [] %>
  <% stack.push(@root)  %>

  <% loop do %>

      <% current_node = stack.last %>


      <% if current_node.parent_opinion == nil %>
          // if not parent, so it is root
          parentNode = main

      <% else %>
          // Locate Parent Node

          parentNode = $("#opinion-<%=current_node.parent_opinion.id%> > #children")


      <%end%>

      parentNode.append("<%= escape_javascript(render 'layouts/opinion', :opinion => current_node, :discussion => @discussion )%>");

      <% stack.pop %>


      <%if current_node.children.size != 0
          current_node.children.not.where(:body => nil).reverse.each do |opinion|

            stack.push(opinion)
          end
        end
      %>

      <% break if stack.empty? %>


  <% end %>

  }

  function orderRelevance(){

  <% hash = {} %>
  <%@discussion.opinions.not.where(:body => nil).each do |opinion| %>
      <% hash[opinion] = opinion.absolute_relevancy() %>
  <% end %>

  <% sorted_hash = hash.sort_by {|_key, value| value}.reverse.to_h
     sorted_hash.take(12).each do |opinion, value| %>
      main.append("Relevância: <%=value%>")
      main.append("<%= escape_javascript(render 'layouts/opinion', :opinion => opinion, :discussion => @discussion )%>");
  <% end %>


  }




  $('.left-bar').each(function() {
  var h = $(this).parent().height();
  $(this).height(h);
  });
<% end %>