config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { :registrations => "users/registrations" }

  resources :discussions do
    resources :opinions do
      get :participation
    end
  end





  devise_scope :user do
    authenticated :user do
      root 'discussions#index', as: :authenticated_root
    end
    unauthenticated do
      root 'users/registrations#new', as: :unauthenticated_root
    end
  end
end

app/views/layouts/_box.html.erb
<%= javascript_tag do %>

    document.getElementById('token').value = opinion;

    if (position == 'up')
    {
        $("#sms").addClass("light-green lighten-4");
        $(".textarea-sms").attr("placeholder", "<%= I18n.t("discussion.opinion_agreement")%>");
    }

    if (position == 'down')
    {
        $("#sms").addClass("red lighten-4");
        $(".textarea-sms").attr("placeholder", "<%= I18n.t("discussion.opinion_disagreement")%>");

    }

    if (position == 'prop')
    {
        $("#sms").addClass("amber lighten-4");
        $(".textarea-sms").attr("placeholder", "<%= I18n.t("discussion.opinion_proposal")%>");
    }

    seeBoxe();



    function seeBoxe(){
    function get_height(elt) {
    return elt.scrollHeight + parseFloat($(elt).css("borderTopWidth")) + parseFloat($(elt).css("borderBottomWidth"));
    }

    $("textarea").keyup(function(e) {
    var found = 0;
    while (!found) {
    $(this).height($(this).height() - 10);
    while($(this).outerHeight() < get_height(this)) {
    $(this).height($(this).height() + 1);
    found = 1;
    };
    }
    });

    var oldVal = "";
    $("textarea").on("change keyup paste", function() {
    var currentVal = $(this).val();
    if(currentVal == oldVal) {
    return; //check to prevent multiple simultaneous triggers
    }

    oldVal = currentVal;
    //action to be performed on textarea changed

    var sendIcon = $('.send').find('i');


    if (!$.trim($("textarea").val())) {

    sendIcon.attr('class', 'mdi-content-clear');
    <!--sendIcon.parent().attr("href", "/opinions/cancel/");-->

    } else {
    sendIcon.attr('class', 'mdi-content-send');
    <!--sendIcon.parent().attr("href", "/opinions/update/"+parent);-->

    }
    });
    }


    $(".form-icon").click(function(e) {

    e.preventDefault();

    sendIcon = $('.send').find('i');

    if (sendIcon.hasClass("mdi-content-send"))
    {
        $( ".submit-form" ).trigger("click");
    }


    if (sendIcon.hasClass("mdi-content-clear"))
    {
        $("#sms").remove();
    }

    });


    

<% end %>

<div id="sms" class="send-message">
  <div class="emoji-key valign-wrapper">
    <a><i class="fa fa-smile-o"></i></a>
  </div>
  <div class="message">
    <%= form_for stub, :url => discussion_opinion_path(@discussion, stub)  do |f|%>
        <%= f.hidden_field :id, id: 'token' %>
        <%= f.text_area :body, rows:1, class:"textarea-sms"  %>
        <%= f.submit class: "submit-form", hidden:true %>
    <% end %>
  </div>
  <div class="send valign-wrapper">
    <a class="form-icon" href="">
      <i class="mdi-content-clear"></i>
    </a>
  </div>



</div>

app/views/layouts/_buttons.html.erb
<div class="position">

  <%
     position_up = "fa fa-thumbs-o-up strong"
     position_down = "fa fa-thumbs-o-down strong"
     position_light = "fa fa-lightbulb-o strong"

     if users_who_interacted(opinion.id).include?(current_user)
       case (position_by_user(opinion.id, current_user).first)
         when 'pro'
           position_up = position_up << " up"
         when 'against'
           position_down = position_down << " down"
         when 'proposal'
           position_light = position_light << " prop"
       end
     end
  %>


  <%= link_to discussion_opinion_participation_path(@discussion.id, opinion.id,  :params => {position: 'up'}), remote: true, class:"btn-up-#{opinion.id}" do %>
      <i id="up-<%= opinion.id %>" class="<%=position_up%>"><span class="d"> Concordar</span><span class="n"><%= relevancy_numbers(opinion.id, "pro" )%></span></i>
  <% end %>
  <%= link_to  discussion_opinion_participation_path(@discussion.id, opinion.id, :params => {position: 'down'}), remote: true, class:"btn-down-#{opinion.id}" do %>
      <i id="down-<%= opinion.id %>" class="<%=position_down%>"><span class="d"> Discordar</span><span class="n"><%= relevancy_numbers(opinion.id, "against" )%></span></i>
  <% end %>
  <% if @discussion.proposal_enabled %>
      <%= link_to  discussion_opinion_participation_path(@discussion.id, opinion.id, :params => {position: 'prop'}), remote: true, class:"btn-prop-#{opinion.id}" do %>
          <i id="prop-<%= opinion.id %>" class="<%=position_light%>"><span class="d"> Propor</span><span class="n"><%= relevancy_numbers(opinion.id, "proposal" )%></span></i>
      <% end %>
  <% end %>
</div>


<% content_for :js do %>

    $('body').bind('ajax:success',
    function(event, xhr, status, header){
    response = JSON.parse(header.getResponseHeader('result'));


    controller = response.controller

    if (controller == "participation")
    {
    parent = response.parent
    opinion = response.opinion
    position = response.position
    status = response.status



    var upButton = $("."+"btn-" + "up" + "-"+ parent)
    var downButton = $("."+"btn-" + "down" + "-"+ parent)
    var propButton = $("."+"btn-" + "prop" + "-"+ parent)

    // Adding One Boxe

    var sms = $("#sms")

    if (status == 'deleted')
    {

    if (position == "up")
    {
    upButton.find("i").removeClass("up");
    sms.remove();
    location.reload();
    }
    if (position == "down")
    {
    downButton.find("i").removeClass("down");
    sms.remove();
    location.reload();
    }
    if (position == "prop")
    {
    propButton.find("i").removeClass("prop");
    sms.remove();
    location.reload();
    }

    // New Values

    upButton.find(".n").text(response.pro)
    downButton.find(".n").text(response.against)
    propButton.find(".n").text(response.proposal)

    }

    if (status == 'impossible to delete')
    {
        location.reload();
    }

    if (status == 'saved')
    {
    if (position == "up")
    {
    upButton.find("i").addClass("up");
    downButton.find("i").removeClass("down");
    propButton.find("i").removeClass("prop");
    }
    if (position == "down")
    {
    downButton.find("i").addClass("down");
    upButton.find("i").removeClass("up");
    propButton.find("i").removeClass("prop");
    }
    if (position == "prop")
    {
    propButton.find("i").addClass("prop");
    downButton.find("i").removeClass("down");
    upButton.find("i").removeClass("up");
    }

    // New Values

    upButton.find(".n").text(response.pro)
    downButton.find(".n").text(response.against)
    propButton.find(".n").text(response.proposal)



        if ($('#sms') == null)
        {
            $("#"+"spaceBox"+"-"+parent).find("#spaceBox").append("<%= escape_javascript(render 'layouts/box')%>");
        }
        else
        {
            $('#sms').remove();

            $("#"+"spaceBox"+"-"+parent+ "").append("<%= escape_javascript(render 'layouts/box')%>");
        }
    }

    }

    if (controller == "cancel")
    {
        $('#sms').remove();
    }


  });



<% end %>

app/views/layouts/_navbar.html.erb
<nav class="grey darken-1">
  <div class="nav-wrapper">
    <a class="brand-logo center hide-on-small-and-down" href="">
      <%= image_tag("mapa.png") %>
      Teste Participativo
    </a>

    <a href="" data-activates="mobile" class="button-collapse"><i class="mdi-action-list"></i></a>

    <% if user_signed_in? %>
        <ul class="left hide-on-med-and-down">
        <li><a class="tooltipped" data-delay="50" data-position="bottom" data-tooltip="<%= I18n.t("discussion.discussion_list") %>" href="<%= discussions_path %>">
          <i class="mdi-navigation-arrow-back"></i></a></li>
        </ul>
    <% end %>
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
      <li><a class="tooltipped" data-delay="50" data-method="delete" data-position="bottom" data-tooltip="<%= I18n.t("devise.sessions.sign_out") %>" href="<%= destroy_user_session_path %>">
        <i class="mdi-action-exit-to-app"></i>
      </a></li>
      <% end %>
    </ul>

    <ul class="side-nav" id="mobile">
      <% if user_signed_in? %>
          <li><a class="tooltipped" data-delay="50" data-position="bottom" data-tooltip="<%= I18n.t("discussion.discussion_list") %>" href="<%= discussions_path %>">
            <i class="mdi-navigation-arrow-back">Voltar</i></a></li>
          <li><a class="tooltipped" data-delay="50" data-method="delete" data-position="bottom" data-tooltip="<%= I18n.t("devise.sessions.sign_out") %>" href="<%= destroy_user_session_path %>">
            <i class="mdi-action-exit-to-app">Sair</i>
          </a></li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/_opinion.html.erb
<%

   case opinion.parent_position
     when 'pro'
        bar = "green lighten-1"

     when 'against'
        bar = "red lighten-1"

     when 'proposal'
        bar = "amber lighten-1"
   end

%>

<div class="argument" id="opinion-<%=opinion.id%>">
  <div class="content card-panel">
    <div class="left-bar <%=bar%>"> </div>
    <div class="ab">

    <div class="text">
          <p><%= opinion.body %></p>
    </div>

    <div class="author">
          <a href="" class="user"><%= opinion.user.name %></a> em <span class="date"><%=
          distance_of_time_in_words(Time.now, opinion.updated_at) %></span>

    </div>
      <p><%= link_to "Veja o Contexto desta Opinião", discussion_opinion_path(@discussion, opinion), method: :get %></p>


      <%= render 'layouts/buttons', opinion: opinion%>
    </div>
    <div id="spaceBox-<%=opinion.id%>" class="spacebox">
    </div>
    </div>
  <div id="children" class="">
  </div>
</div>

app/views/layouts/_toast.html.erb
<% if flash[:notice] -%>
    <%= javascript_tag "Materialize.toast('#{flash[:notice]}', 4000)" %>
<% end %>

<% if flash[:error] -%>
    <%= javascript_tag "Materialize.toast('#{flash[:error]}', 4000)" %>
<% end %>

<% if flash[:success] -%>
    <%= javascript_tag "Materialize.toast('#{flash[:success]}', 4000)" %>
<% end %>

<% if flash[:info] -%>
    <%= javascript_tag "Materialize.toast('#{flash[:info]}', 4000)" %>
<% end %>

<% if flash[:alert] -%>
    <%= javascript_tag "Materialize.toast('#{flash[:alert]}', 4000)" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= render_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= include_gon(init: true) %>

</head>
<body class="grey lighten-2">


<%= render partial: "layouts/toast" %>
<%= render partial: "layouts/navbar" %>
<%= yield %>

<script>
    <%= yield :js %>
</script>
</body>
</html>